#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND %BUILD_REQ);

%RECOMMEND = ();

%BUILD_REQ = (
   'Test::More'      => '0.40',
   'Test::Sys::Info' => '0.13',
);

%PREREQ = (
   'IO::File'                   => 0,
   'Sys::Info::Base'            => '0.70',
   'Sys::Info::Driver::Unknown' => '0.70',
   'ExtUtils::CBuilder'         => 0,
   'Win32::OLE'                 => 0,
);

1;
